# Vietnam

In [3]:
# text = "căn biệt phủ của ông bùi cách tuyến chỉ rộng 120 m2"
# text = "+ mỗi vé có một số series và không trùng nhau + có nhiều số series trùng nhau .\n"
text = "được biết trước khi làm chủ tịch ubnd huyện côn đảo , ông chính công tác tại bộ chỉ huy quân sự tỉnh bà rịa - vũng tàu ."

## MBART

In [4]:
from transformers import MBartTokenizer
from text import text_to_sequence

In [5]:
tokenizer = MBartTokenizer.from_pretrained('facebook/mbart-large-cc25')

In [6]:
ids = tokenizer("</s>" + text + "</s> vi_VN", add_special_tokens=False, return_tensors='pt')['input_ids']
print(ids[0])

tensor([     2,    912,   4022,   5179,   1907,   1839,   6657,  40443,      6,
          5829,   2208,  62633,   4747,     19,  54520,      6,      4,   5718,
          3178,   1871,   6330,   2251,   5830,   2524,  58854,  29225,   2550,
         17501,  15409,   1690,  51721,     11,     20,     81, 145131,  72894,
             6,      5,      2, 250024])


In [7]:
token = tokenizer.convert_ids_to_tokens(ids[0])
print(token)

['</s>', '▁được', '▁biết', '▁trước', '▁khi', '▁làm', '▁chủ', '▁tịch', '▁', 'ub', 'nd', '▁huyện', '▁cô', 'n', '▁đảo', '▁', ',', '▁ông', '▁chính', '▁công', '▁tác', '▁tại', '▁bộ', '▁chỉ', '▁huy', '▁quân', '▁sự', '▁tỉnh', '▁bà', '▁r', 'ị', 'a', '▁-', '▁v', 'ũng', '▁tàu', '▁', '.', '</s>', 'vi_VN']


## BARTPho

In [8]:
from transformers import AutoTokenizer

In [9]:
tokenizer = AutoTokenizer.from_pretrained("vinai/bartpho-syllable", use_fast=False)

In [10]:
ids = tokenizer(text, return_tensors='pt')['input_ids']
print(ids[0])

tensor([    0,    11,    88,   127,    26,    50,   168,   499,    23, 10982,
         7148,   435,   200,    19,   738,    23,     4,    69,    74,    25,
          139,    34,   123,    68,   891,   298,    54,   223,   329,   339,
         1289,    97,    33,   258,  2081,   537,    23,     5,     2])


In [11]:
token = tokenizer.convert_ids_to_tokens(ids[0])
print(token)

['<s>', '▁được', '▁biết', '▁trước', '▁khi', '▁làm', '▁chủ', '▁tịch', '▁', 'ub', 'nd', '▁huyện', '▁cô', 'n', '▁đảo', '▁', ',', '▁ông', '▁chính', '▁công', '▁tác', '▁tại', '▁bộ', '▁chỉ', '▁huy', '▁quân', '▁sự', '▁tỉnh', '▁bà', '▁r', 'ị', 'a', '▁-', '▁v', 'ũng', '▁tàu', '▁', '.', '</s>']


## PhoBERT

In [23]:
import torch
from transformers import AutoTokenizer
from text import text_to_sequence, sequence_to_text

In [13]:
tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-large", use_fast=False)

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [14]:
ids = torch.tensor([tokenizer.encode(text)])
ids[0]

tensor([    0,    11,    55,    71,    26,    47,   286, 26865, 29494, 26189,
          149, 12840,   705,     4,    46,   159,   675, 18116,    35,   215,
           66, 23250,   829,    61,    98,   155,  1698, 40687,    31, 11953,
          356,     5,     2])

In [24]:
token = tokenizer.convert_ids_to_tokens(ids[0])
print(token)

['<s>', 'được', 'biết', 'trước', 'khi', 'làm', 'chủ', 'tịch', 'ub@@', 'nd', 'huyện', 'côn', 'đảo', ',', 'ông', 'chính', 'công', 'tác', 'tại', 'bộ', 'chỉ', 'huy', 'quân', 'sự', 'tỉnh', 'bà', 'r@@', 'ịa', '-', 'vũng', 'tàu', '.', '</s>']


# English

In [25]:
text = "When asked to explain the similarity of characteristics, Cadigan stated, quote, well briefly"

In [26]:
def add_cls_sep(text):
    return "[CLS] " + text + " [SEP]"

In [27]:
s = text_to_sequence(text, ["english_cleaners"])
print(s)

[96, 48, 34, 59, 11, 12, 81, 56, 34, 32, 11, 82, 60, 11, 34, 97, 78, 57, 12, 49, 59, 11, 82, 48, 34, 11, 81, 49, 58, 49, 57, 12, 80, 49, 82, 98, 11, 60, 46, 11, 31, 48, 12, 80, 12, 31, 82, 34, 80, 49, 81, 82, 49, 31, 81, 6, 11, 31, 12, 32, 49, 47, 12, 59, 11, 81, 82, 12, 82, 34, 32, 6, 11, 79, 83, 60, 82, 34, 6, 11, 96, 34, 57, 57, 11, 30, 80, 49, 34, 46, 57, 98]


In [28]:
text_cleaned = sequence_to_text(s)
print(text_cleaned)

when asked to explain the similarity of characteristics, cadigan stated, quote, well briefly


## BERT 
### HuggingFace

In [29]:
import torch
from transformers import BertTokenizer, BertModel
from text import text_to_sequence, sequence_to_text

In [30]:
model_bert = BertModel.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [31]:
text_processed = add_cls_sep(text_cleaned)
tokenized_text = tokenizer.tokenize(text_processed)
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
segments_ids = [0 for i in range(len(indexed_tokens))]
tokens_tensor = torch.tensor([indexed_tokens])
segments_tensors = torch.tensor([segments_ids])
print(tokens_tensor)
print(segments_tensors)

tensor([[  101,  2043,  2356,  2000,  4863,  1996, 14402,  1997,  6459,  1010,
         28353, 10762,  3090,  1010, 14686,  1010,  2092,  4780,   102]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


In [34]:
with torch.no_grad():
    print(model_bert(tokens_tensor, segments_tensors)[0][0].shape)
    print("-----------------")
    print(model_bert(tokens_tensor, segments_tensors)[1].shape)
    encoded_layers = model_bert(tokens_tensor, segments_tensors)[0]
    print(encoded_layers)

torch.Size([19, 768])
-----------------
torch.Size([1, 768])
tensor([[[-0.0352,  0.2057, -0.6240,  ..., -0.1726,  0.4053,  0.3813],
         [-0.2486,  0.0666, -0.5241,  ...,  0.3820,  0.3803, -0.0616],
         [-0.0244, -0.4694, -0.1529,  ...,  0.3105, -0.0269, -0.3088],
         ...,
         [ 0.5606,  0.3519,  0.5786,  ...,  0.1516, -0.2715, -0.1949],
         [-0.1893, -0.0686, -0.4035,  ...,  0.7745,  0.1391, -0.1611],
         [ 0.7732,  0.3311, -0.3702,  ...,  0.6668, -0.8738, -0.3741]]])


## BERT 
### pytorch_pretrained_bert

In [ ]:
from pytorch_pretrained_bert import BertTokenizer, BertModel

In [ ]:
model_bert = BertModel.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [ ]:
text_processed = add_cls_sep(text_cleaned)
tokenized_text = tokenizer.tokenize(text_processed)
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
segments_ids = [0 for i in range(len(indexed_tokens))]
tokens_tensor = torch.tensor([indexed_tokens])
segments_tensors = torch.tensor([segments_ids])
print(tokens_tensor)
print(segments_tensors)

tensor([[  101,  2043,  2356,  2000,  4863,  1996, 14402,  1997,  6459,  1010,
         28353, 10762,  3090,  1010, 14686,  1010,  2092,  4780,   102]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


In [ ]:
with torch.no_grad():
    print(model_bert(tokens_tensor, segments_tensors)[0][11][0].shape)
    print("--------------")
    print(model_bert(tokens_tensor, segments_tensors)[1].shape)

torch.Size([19, 768])
--------------
torch.Size([1, 768])


## BERT 
### multilingual

In [73]:
text_en = "When asked to explain the similarity of characteristics, Cadigan stated, quote, well briefly"
text_vi = "được biết trước khi làm chủ tịch ubnd huyện côn đảo , ông chính công tác tại bộ chỉ huy quân sự tỉnh bà rịa - vũng tàu ."

In [74]:
import torch
from transformers import BertTokenizer, BertModel
from text import text_to_sequence, sequence_to_text

In [75]:
model_bert = BertModel.from_pretrained('bert-base-multilingual-cased')
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

Downloading: 100%|██████████| 625/625 [00:00<00:00, 732kB/s]
Downloading: 100%|██████████| 681M/681M [01:31<00:00, 7.83MB/s] 
Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Downloading: 100%|

In [76]:
def add_cls_sep(text):
    return "[CLS] " + text + " [SEP]"

### vietnam

In [78]:
s = text_to_sequence(text_vi, ["basic_cleaners"])
print(s)
text_cleaned = sequence_to_text(s)
print(text_cleaned)

[33, 89, 77, 31, 11, 30, 49, 41, 82, 11, 82, 80, 89, 73, 31, 11, 56, 48, 49, 11, 57, 15, 58, 11, 31, 48, 85, 11, 82, 54, 31, 48, 11, 83, 30, 59, 32, 11, 48, 83, 98, 45, 59, 11, 31, 66, 59, 11, 33, 14, 60, 11, 6, 11, 66, 59, 47, 11, 31, 48, 50, 59, 48, 11, 31, 66, 59, 47, 11, 82, 13, 31, 11, 82, 17, 49, 11, 30, 71, 11, 31, 48, 51, 11, 48, 83, 98, 11, 79, 83, 18, 59, 11, 81, 94, 11, 82, 51, 59, 48, 11, 30, 15, 11, 80, 54, 12, 11, 1, 11, 95, 87, 59, 47, 11, 82, 15, 83, 11, 7]
được biết trước khi làm chủ tịch ubnd huyện côn đảo , ông chính công tác tại bộ chỉ huy quân sự tỉnh bà rịa - vũng tàu .


In [79]:
text_processed = add_cls_sep(text_cleaned)
tokenized_text = tokenizer.tokenize(text_processed)
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
segments_ids = [0 for i in range(len(indexed_tokens))]
tokens_tensor = torch.tensor([indexed_tokens])
segments_tensors = torch.tensor([segments_ids])
print(tokenized_text)
print(tokens_tensor)
print(segments_tensors)

['[CLS]', 'được', 'biết', 'trước', 'khi', 'làm', 'chủ', 'tịch', 'u', '##bn', '##d', 'huyện', 'côn', 'đảo', ',', 'ông', 'chính', 'công', 'tác', 'tại', 'bộ', 'chỉ', 'huy', 'quân', 'sự', 'tỉnh', 'bà', 'r', '##ị', '##a', '-', 'vũ', '##ng', 'tàu', '.', '[SEP]']
tensor([[  101, 10476, 21820, 16325, 12072, 12984, 16549, 41946,   189, 71136,
         10162, 15222, 84547, 22587,   117, 12660, 12707, 12319, 17976, 12086,
         13848, 14294, 33901, 12488, 12636, 14221, 27083,   186, 30324, 10113,
           118, 36108, 10376, 19415,   119,   102]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


### english

In [80]:
s = text_to_sequence(text_en, ["basic_cleaners"])
print(s)
text_cleaned = sequence_to_text(s)
print(text_cleaned)

[96, 48, 34, 59, 11, 12, 81, 56, 34, 32, 11, 82, 60, 11, 34, 97, 78, 57, 12, 49, 59, 11, 82, 48, 34, 11, 81, 49, 58, 49, 57, 12, 80, 49, 82, 98, 11, 60, 46, 11, 31, 48, 12, 80, 12, 31, 82, 34, 80, 49, 81, 82, 49, 31, 81, 6, 11, 31, 12, 32, 49, 47, 12, 59, 11, 81, 82, 12, 82, 34, 32, 6, 11, 79, 83, 60, 82, 34, 6, 11, 96, 34, 57, 57, 11, 30, 80, 49, 34, 46, 57, 98]
when asked to explain the similarity of characteristics, cadigan stated, quote, well briefly


In [81]:
text_processed = add_cls_sep(text_cleaned)
tokenized_text = tokenizer.tokenize(text_processed)
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
segments_ids = [0 for i in range(len(indexed_tokens))]
tokens_tensor = torch.tensor([indexed_tokens])
segments_tensors = torch.tensor([segments_ids])
print(tokenized_text)
print(tokens_tensor)
print(segments_tensors)

['[CLS]', 'when', 'asked', 'to', 'explain', 'the', 'similar', '##ity', 'of', 'characteristics', ',', 'ca', '##digan', 'stated', ',', 'quo', '##te', ',', 'well', 'briefly', '[SEP]']
tensor([[  101, 10841, 22151, 10114, 67004, 10105, 13213, 11949, 10108, 40582,
           117, 11135, 66637, 17067,   117, 48718, 10216,   117, 11206, 36327,
           102]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
